### ISSUE TITLE
Comparison to official MetaTrader module for integration with Python

### ISSUE THREAD

**Issue by jmakov** [darwinex/dwxconnect#31]
Hi,
first thanks for your work! I stumbled upon https://www.mql5.com/en/docs/integration/python_metatrader5 and am wondering how is `dwconnect` different (other than it can also be used with other languages). And if there are any limitations.

**Comment by piotryordanov** [comment]
You can't do on_tick this way in the python implementation.
That along with other stuff

**Comment by jmakov** [comment]
> You can't do on_tick this way in the python implementation. That along with other stuff

Not clear which python implementation you mean - dwxconnect or MT5? Also what other stuff? :)

**Comment by piotryordanov** [comment]
With the python implementation of MQL, you are unable to watch for events. 
YOu have to instead poll yourself.

With DWX, you don't have to worry about it, because that is done directly by using the file system vs, say, a socket.
If you do want to use sockets to communicate between MQL and python, you need to enable them in Terminal. And it is quite unreliable.

Also, the python implementation only work under windows as that's where the pip package is. This means that u have to be under wine.
The DWX_Connect does not need to be under windows, thus making it more robust and simple to develop with it.

**Comment by jmakov** [comment]
Thanks for the clarification!
